export const EXAMPLES: { tool: string; phrases: string[] }[] = [
  {
    tool: "weather_request",
    phrases: [
      "What's the weather in Tokyo?",
      "Is it raining in London?",
      "What's the temperature in New York?",
      "How's the weather in Paris today?",
      "Will it snow in Kyiv this week?",
      "Weather forecast for Berlin",
      "Is it sunny in Sydney?",
      "Should I bring an umbrella in Seattle?",
      "What's the weather like in Dubai?",
      "How cold is it in Chicago?",
      "Weather in Miami right now",
      "Is it hot in Phoenix?",
      "Tell me the weather for Toronto",
      "Current weather in Los Angeles",
    ],
  },
  {
    tool: "movie_request",
    phrases: [
      "Show me top movies",
      "What are the best movies right now?",
      "Search for Avatar",
      "Find the movie Inception",
      "Top rated films this year",
      "Look up movies by Christopher Nolan",
      "Popular movies 2026",
      "Trending films right now",
      "Search movies with Tom Hanks",
      "Best action movies",
      "Find movie Zootopia 2",
      "What movies are popular?",
    ],
  },
  {
    tool: "music_request",
    phrases: [
      "What are the top songs?",
      "Search for Taylor Swift",
      "Best albums this year",
      "Find music by Kendrick Lamar",
      "Top hits right now",
      "Search for J. Cole albums",
      "Popular songs 2026",
      "Trending music",
      "Look up music by Drake",
      "Best rap albums",
      "Find songs by The Weeknd",
      "What music is popular?",
    ],
  },
  {
    tool: "skip_api_call",
    phrases: [
      "Tell me a joke",
      "Who are you?",
      "Hello",
      "What can you do?",
      "Help me",
      "How are you?",
      "What is the meaning of life?",
      "Tell me something interesting",
      "What's 2 + 2?",
      "Good morning",
      // Cross-domain references to prior results
      "I'll go see that movie and listen to the album you recommended",
      "Sounds like a plan, the movie and the album both look great",
      "Nice, both the film and the music have good ratings",
      // Confirmation questions about prior results
      "Am I right about that rating?",
      "So the rating was 8.8, right?",
      "Is that correct based on what you showed me?",
      // Meta-comments / complaints about assistant behavior
      "Why did you mention that?",
      "That's not what I asked about",
      "I didn't ask for weather",
      "Why are you talking about weather?",
      "Stop bringing up weather, that's wrong",
      "I never asked about weather, what are you doing?",
      "You keep mentioning weather for no reason",
      "That weather response was completely wrong",
      "Don't talk about movies, I asked something else",
      "Why do you keep suggesting music?",
    ],
  },
];
